#This file was originally generated by PyScripter's unitest wizard

import unittest
import GuiQwtPlot_temperature

class TestOpenFilesTool(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testget_filenames(self):
        pass

    def testactivate_command(self):
        pass

class TestRefreshTool(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testactivate_command(self):
        pass

class TestProducer(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass


    def testproduce(self):
        pass

    def teststart_timer(self):
        pass

class TestGuiQwtPlot(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test__read_temperature_data(self):
        pass

    def test__datestr2mktime(self):
        teststrs = [('14/01/2013 2:06:08 pm', [2013,1,14,14,6,8,0,0,0]),
                    ('7/11/2012 11:12:41 am', [2012,11,7,11,12,41,0,0,0]),
                    ('8/06/2012 11:08:05 a.m.',[2012,6,8,11,8,5,0,0,0]),
                    ('8/06/2012 11:08:05 am', [2012,6,8,11,8,5,0,0,0])]
        for teststr in teststrs:
            self.assertEqual(GuiQwtPlot_temperature.teststr[1],)


    def testopen_file(self):
        pass

    def testupdate(self):
        pass

    def testcloseEvent(self):
        pass

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testmain(self):
        pass

if __name__ == '__main__':
    unittest.main()
